version: 2.1
jobs:
  lint212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  lint212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.2_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  test212_jdk8:
    docker:
      - image: hseeberger/scala-sbt:8u181_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! test:run
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  test212_jdk11:
    docker:
      - image: hseeberger/scala-sbt:11.0.2_2.12.8_1.2.8
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt ++2.12.8! test:run
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  build:
    jobs:
      - lint212_jdk8
      - lint212_jdk11
      - test212_jdk8:
          requires:
            - lint212_jdk8
      - test212_jdk11:
          requires:
            - lint212_jdk11
